### ISSUE TITLE
[Bug Report]: "Git not found in the current environment" (VSC-752)

### ISSUE THREAD

**Issue by maelp** [espressif/vscode-esp-idf-extension#522] opened 2021-09-09 07:46 UTC
**Describe the bug**
When starting the extension, it shows "Git not found in the current environment" although in the extension settings the git path is set to the correct (full) path of git, and the extension stops loading

**To Reproduce**
Loading the extension

**Expected behavior**
The extension should load and find Git at the proper path

**Screenshots**
![image](https://user-images.githubusercontent.com/15458/132644006-8ab0d778-b75a-4921-bd7b-8760a499124a.png)

**Environment (please complete the following information):**

- OS Name & Version: osX (git installed using brew, or nix)
- VSCode Version: 1.60.0
- ESP-IDF Version: v1.1.1
- Python Version: 3.9.4

Although when running the "ESP-IDF Doctor" command I see:

OS darwin x64 20.6.0 
Visual Studio Code version 1.60.0 
Visual Studio Code language en 
Visual Studio Code shell zsh 
ESP-IDF Extension version 1.1.1 
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) ${env:IDF_PATH}
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
Custom extra paths (idf.customExtraPaths) 
Custom extra vars (idf.customExtraVars) 
Virtual env Python Path (idf.pythonBinPath) /Users/primet/.nix-profile/bin/python
Serial port (idf.port) /dev/ttyUSB1
OpenOCD Configs (idf.openOcdConfigs) interface/ftdi/esp32_devkitj_v1.cfg,board/esp32-wrover.cfg
ESP-IDF Tools Path (idf.toolsPath) ${env:IDF_TOOLS_PATH}
Git Path (idf.gitPath) /usr/local/Cellar/git/2.33.0/bin/git
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espIdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) false
Access to ESP-MDF Path (idf.espIdfPath) false
Access to ESP-IDF Custom extra paths
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH true
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) false
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version undefined
ESP-IDF version undefined
Python version undefined
Python's pip version undefined
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages undefined
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages undefined
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages undefined
----------------------------------------------------------- Latest error -----------------------------------------------------------------
Latest error at Command failed: which ninja

--------------------------------------------------------------------------------------------------------------------------------------------

**Comment by brianignacio5** [comment] 2021-09-09 11:35
This is a duplicate of #506 

Based on the doctor command output you are missing ninja-build from your system. It is mentioned in the [readme prerequisites section](https://github.com/espressif/vscode-esp-idf-extension#prerequisites), in [ESP-IDF](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/linux-setup.html) and the setup window text itself.

Another thing I noticed is that git version is undefined for some reason. Is git available in PATH ?

For some reason the error message being shown is "git is not found" probably because the error being captured is somehow replaced. This should be fixed on GitHub master and we will release a new version soon.

**Closed by brianignacio5** 2021-09-09 11:35 UTC
Labels: duplicate
