### ISSUE TITLE
can't config,always show ESP-IDF Extension for Visual Studio Code Welcome. restart Visual Studio Code and run this wizard again. (VSC-999)

### ISSUE THREAD

**Issue by Dozingfiretruck** [espressif/vscode-esp-idf-extension#829] opened 2022-11-01 03:54 UTC
### OS

Windows

### Operating System version

windows10

### Visual Studio Code version

1.5

### ESP-IDF version

5.0

### Python version

3.8

### Doctor command output

no

### Description

can't config,always show ESP-IDF Extension for Visual Studio Code Welcome. restart Visual Studio Code and run this wizard again.

### Debug Message

```plain
no
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment] 2022-11-01 08:10
This is duplicate of #813 and #823 and is fixed already in GitHub master, marketplace release will come out soon !

The issue is fixed in master. Also please fill the issue template properly, without this information we can't understand your specific environment issue.

**Closed by brianignacio5** 2022-11-01 08:10 UTC
Labels: duplicate, bug-report
