### ISSUE TITLE
[Bug Report]: Compilation warnings do not appear in the Problems tab (VSC-939)

### ISSUE THREAD

**Issue by ademenev** [espressif/vscode-esp-idf-extension#764] opened 2022-07-21 12:43 UTC
**Pre Bug Report Checklist**
Before reporting any bug please make sure of these points.

- [X] Make sure you have searched for existing bugs and features request before you post an issue.
- [X] This is a bug report for the ESP-IDF Visual Studio Code extension and **not** an ESP-IDF bug report.
- [X] I've read the docs and found no information that could have helped solving the issue.

**Describe the bug**
Compilation warnings not displayed in "Problems" tab. The warnings appear in the tab for a very short time, and then disappear. If the compiler generates error(s) **and** warnings,  then the errors and warnings are displayed

**To Reproduce**
Build any project with compiler warnings (for example, unused static functions)

**Expected behavior**
Warnings displayed in "Problems" tab

**Environment (please complete the following information):**

<details>
<summary> Output of Doctor command</summary>

```
---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS darwin x64 19.6.0 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/CrossPack-AVR/bin 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.69.2 
Visual Studio Code language en 
Visual Studio Code shell /bin/zsh 
ESP-IDF Extension version 1.4.0 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) /Users/andrey/esp/esp-idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
Custom extra paths (idf.customExtraPaths) /Users/andrey/.espressif/tools/xtensa-esp32-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32-elf/bin:/Users/andrey/.espressif/tools/xtensa-esp32s2-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32s2-elf/bin:/Users/andrey/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32s3-elf/bin:/Users/andrey/.espressif/tools/riscv32-esp-elf/esp-2021r2-patch3-8.4.0/riscv32-esp-elf/bin:/Users/andrey/.espressif/tools/esp32ulp-elf/2.28.51-esp-20191205/esp32ulp-elf-binutils/bin:/Users/andrey/.espressif/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin:/Users/andrey/.espressif/tools/cmake/3.20.3/CMake.app/Contents/bin:/Users/andrey/.espressif/tools/openocd-esp32/v0.11.0-esp32-20211220/openocd-esp32/bin:/Users/andrey/.espressif/tools/ninja/1.10.2
Custom extra vars (idf.customExtraVars) {"OPENOCD_SCRIPTS":"/Users/andrey/.espressif/tools/openocd-esp32/v0.11.0-esp32-20211220/openocd-esp32/share/openocd/scripts"}
Virtual env Python Path (idf.pythonBinPath) /Users/andrey/.espressif/python_env/idf4.4_py3.10_env/bin/python
Serial port (idf.port) /dev/cu.SLAB_USBtoUART
OpenOCD Configs (idf.openOcdConfigs) interface/ftdi/esp32_devkitj_v1.cfg,target/esp32.cfg
ESP-IDF Tools Path (idf.toolsPath) /Users/andrey/.espressif
Git Path (idf.gitPath) git
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-IDF Custom extra paths
Access to /Users/andrey/.espressif/tools/xtensa-esp32-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32-elf/bin: true
Access to /Users/andrey/.espressif/tools/xtensa-esp32s2-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32s2-elf/bin: true
Access to /Users/andrey/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32s3-elf/bin: true
Access to /Users/andrey/.espressif/tools/riscv32-esp-elf/esp-2021r2-patch3-8.4.0/riscv32-esp-elf/bin: true
Access to /Users/andrey/.espressif/tools/esp32ulp-elf/2.28.51-esp-20191205/esp32ulp-elf-binutils/bin: true
Access to /Users/andrey/.espressif/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin: true
Access to /Users/andrey/.espressif/tools/cmake/3.20.3/CMake.app/Contents/bin: true
Access to /Users/andrey/.espressif/tools/openocd-esp32/v0.11.0-esp32-20211220/openocd-esp32/bin: true
Access to /Users/andrey/.espressif/tools/ninja/1.10.2: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH true
Access to Ninja in environment PATH true
Access to ESP-IDF Tools Path (idf.toolsPath) true
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.27.0
ESP-IDF version 4.4.1
Python version 3.10.5
Python's pip version 22.1.2
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitstring version: 3.1.9
Brotli version: 1.0.9
certifi version: 2022.6.15
cffi version: 1.15.1
charset-normalizer version: 2.1.0
click version: 8.1.3
colorama version: 0.4.5
construct version: 2.10.54
contextlib2 version: 21.6.0
cryptography version: 37.0.4
ecdsa version: 0.18.0
Flask version: 0.12.5
Flask-Compress version: 1.12
Flask-SocketIO version: 2.9.6
future version: 0.18.2
gcovr version: 5.1
gdbgui version: 0.13.2.0
gevent version: 1.5.0
greenlet version: 1.1.2
idf-component-manager version: 1.1.4
idna version: 3.3
itsdangerous version: 2.0.1
Jinja2 version: 3.0.3
kconfiglib version: 13.7.1
lxml version: 4.9.1
MarkupSafe version: 2.1.1
pip version: 22.1.2
psutil version: 5.9.1
pycparser version: 2.21
pyelftools version: 0.28
pygdbmi version: 0.9.0.2
Pygments version: 2.12.0
pyparsing version: 2.3.1
pyserial version: 3.5
python-engineio version: 3.14.2
python-socketio version: 4.6.1
PyYAML version: 6.0
reedsolo version: 1.5.4
requests version: 2.28.1
requests-toolbelt version: 0.9.1
schema version: 0.7.5
setuptools version: 63.2.0
six version: 1.16.0
tqdm version: 4.64.0
urllib3 version: 1.26.10
websocket-client version: 1.3.3
Werkzeug version: 0.16.1
wheel version: 0.37.1
xmlrunner version: 1.7.7
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements from /Users/andrey/esp/esp-idf/requirements.txt are satisfied.
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages Python requirements from /Users/andrey/.vscode/extensions/espressif.esp-idf-extension-1.4.0/requirements.txt are satisfied.
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Python requirements from /Users/andrey/.vscode/extensions/espressif.esp-idf-extension-1.4.0/esp_debug_adapter/requirements.txt are satisfied.
---------------------------------------------------- Visual Studio Code launch.json --------------------------------------------------------
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch"
    }
  ]
} 
---------------------------------------------------- Visual Studio Code c_cpp_properties.json ----------------------------------------------
{
    "configurations": [
        {
            "name": "ESP-IDF",
            "compilerPath": "/Users/andrey/.espressif/tools/xtensa-esp32-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "includePath": [
                "${config:idf.espIdfPath}/components/**",
                "${config:idf.espIdfPathWin}/components/**",
                "${config:idf.espAdfPath}/components/**",
                "${config:idf.espAdfPathWin}/components/**",
                "${workspaceFolder}/**"
            ],
            "browse": {
                "path": [
                    "${config:idf.espIdfPath}/components",
                    "${config:idf.espIdfPathWin}/components",
                    "${config:idf.espAdfPath}/components/**",
                    "${config:idf.espAdfPathWin}/components/**",
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": false
            }
        }
    ],
    "version": 4
}
 
--------------------------------------------------------------------------------------------------------------------------------------------

```

</details>

<details>
<summary>**Extension Configuration settings**</summary>

```
{
    "C_Cpp.intelliSenseEngine": "Tag Parser",
    "idf.adapterTargetName": "esp32",
    "idf.customExtraPaths": "/Users/andrey/.espressif/tools/xtensa-esp32-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32-elf/bin:/Users/andrey/.espressif/tools/xtensa-esp32s2-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32s2-elf/bin:/Users/andrey/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32s3-elf/bin:/Users/andrey/.espressif/tools/riscv32-esp-elf/esp-2021r2-patch3-8.4.0/riscv32-esp-elf/bin:/Users/andrey/.espressif/tools/esp32ulp-elf/2.28.51-esp-20191205/esp32ulp-elf-binutils/bin:/Users/andrey/.espressif/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin:/Users/andrey/.espressif/tools/cmake/3.20.3/CMake.app/Contents/bin:/Users/andrey/.espressif/tools/openocd-esp32/v0.11.0-esp32-20211220/openocd-esp32/bin:/Users/andrey/.espressif/tools/ninja/1.10.2",
    "idf.customExtraVars": "{\"OPENOCD_SCRIPTS\":\"/Users/andrey/.espressif/tools/openocd-esp32/v0.11.0-esp32-20211220/openocd-esp32/share/openocd/scripts\"}",
    "idf.espIdfPath": "/Users/andrey/esp/esp-idf",
    "idf.openOcdConfigs": [
        "interface/ftdi/esp32_devkitj_v1.cfg",
        "target/esp32.cfg"
    ],
    "idf.port": "/dev/cu.SLAB_USBtoUART",
    "idf.pythonBinPath": "/Users/andrey/.espressif/python_env/idf4.4_py3.10_env/bin/python",
    "idf.toolsPath": "/Users/andrey/.espressif",
    "idf.flashType": "UART",
    "files.associations": {
        "sdkconfig.h": "c",
        "u8g2_esp32_hal.h": "c",
        "gpio.h": "c",
        "task.h": "c",
        "spi_master.h": "c",
        "u8g2.h": "c",
        "freertos.h": "c",
        "*.tcc": "c",
        "optional": "c",
        "istream": "c",
        "ostream": "c",
        "ratio": "c",
        "system_error": "c",
        "array": "c",
        "functional": "c",
        "regex": "c",
        "tuple": "c",
        "type_traits": "c",
        "utility": "c",
        "random": "cpp",
        "*.inc": "c",
        "stdio.h": "c",
        "esp_log.h": "c",
        "bitset": "cpp",
        "memory": "cpp",
        "future": "cpp"
    }
}

```

</details>

**Comment by brianignacio5** [comment] 2022-07-26 06:56
This might be related to some issues like #748 and #678 and the IDF Size override the terminal from IDF Build task.

Should be fixed in GitHub master.

**Comment by brianignacio5** [comment] 2022-08-01 09:36
Updates ?

Have you tried the GitHub master? This is the [vsix installer link](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/315473533.zip)

**Comment by ademenev** [comment] 2022-08-01 10:22
I tried it right now. The problems tab is still empty. The build task is highlighted in yellow though:

![Снимок экрана 2022-08-01 в 14 19 55](https://user-images.githubusercontent.com/2399220/182128070-9a87bd2b-d9ab-457f-816f-031998b5ddd9.png)

**Comment by brianignacio5** [comment] 2022-08-08 11:54
I tried to reproduce locally in macOS Big Sur 11.6.6 and seems to be working properly
![Screen Shot 2022-08-08 at 7 51 23 PM](https://user-images.githubusercontent.com/6033246/183411905-47714d8c-e9f9-46d7-baa1-a02166e6b91d.png)
![Screen Shot 2022-08-08 at 7 50 40 PM](https://user-images.githubusercontent.com/6033246/183411928-0976bc8d-389f-43c0-9df2-5fd9640fbf6c.png)

Weird. Is the ESP-IDF Terminal running when this happens?

**Comment by brianignacio5** [comment] 2022-08-15 12:20
Any updates? Could you provide some steps to reproduce ?

**Comment by brianignacio5** [comment] 2022-08-17 06:43
Latest test got this results. Closing this issue for lack of response. Please comment here if you still have issues.
![Screen Shot 2022-08-17 at 2 41 23 PM](https://user-images.githubusercontent.com/6033246/185052254-8ff247b7-c3bb-40ce-9f27-acf2087d65fc.png)
![Screen Shot 2022-08-17 at 2 42 13 PM](https://user-images.githubusercontent.com/6033246/185052305-579c7bf1-02e3-4333-aa7d-2f3f6f31fa98.png)

**Closed by brianignacio5** 2022-08-17 06:43 UTC
Labels: bug-report

**Comment by gonczikeve** [comment] 2023-05-14 17:31
I still have this issue. 
idf v4.4/release, installed from the vscode store - so the idf path variables are set locally on vscode
While building, the problems window has the blue icon with the number of issues, but at the moment when the "size" task finishes running, the problems window gets cleared.

Size task still loading:

![Screenshot (283)](https://github.com/espressif/vscode-esp-idf-extension/assets/106698166/b01d2c92-3b1a-448c-abea-7ae1d4697f13)


Everything finished:

![Screenshot (284)](https://github.com/espressif/vscode-esp-idf-extension/assets/106698166/1b628906-983b-4f78-9f8b-9b1fe9d3abfd)

**Comment by eichhornp** [comment] 2023-05-24 09:08
I still have the issue with extension 1.6.2 and esp-idf 4.4.3 .
It behaves like described above

**Comment by brianignacio5** [comment] 2023-05-26 05:39
You can disable the Size task with the `idf.enableSizeTaskAfterBuildTask` in the current master and the next v1.6.3 version.

The problem is that problems are cleared when a new task is executed. As of now tasks don't fail on warning just errors.
