### ISSUE TITLE
"Configure ESP-IDF Extension" is stuck on title screen (VSC-1002)

### ISSUE THREAD

**Issue by chipweinberger** [espressif/vscode-esp-idf-extension#833] opened 2022-11-03 22:00 UTC
### OS

MacOS

### Operating System version

12.5.1

### Visual Studio Code version

1.73.0 (Universal)

### ESP-IDF version

Both v4.4.2 and v5.0

### Python version

Python 3.9.9

### Doctor command output

```
Error checking esp-rom-elfs version
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''
/bin/sh: riscv32-esp-elf-gdb-no-python: command not found
Command failed: riscv32-esp-elf-gdb-no-python --version
/bin/sh: riscv32-esp-elf-gdb-no-python: command not found
Error checking riscv32-esp-elf-gdb version
Error: Command failed: riscv32-esp-elf-gdb-no-python --version
/bin/sh: riscv32-esp-elf-gdb-no-python: command not found
```

### Extension

[esp_idf_vsc_ext.log](https://github.com/espressif/vscode-esp-idf-extension/files/9933273/esp_idf_vsc_ext.log)

[report.json.txt](https://github.com/espressif/vscode-esp-idf-extension/files/9933390/report.json.txt)

### Description

I was on v4.4.2

I reconfigured to v5.0, it worked.

I'm now stuck on the title screen. I've tried restarting & reinstalling ESP-IDF VSC Extension. 

I cannot get past the title screen to reconfigure again.

Note: building with cmd line (idf.py build) works.

Title Screen (note: Express, Custom, Advanced options are missing):
<img width="637" alt="Screen Shot 2022-11-03 at 2 51 35 PM" src="https://user-images.githubusercontent.com/1863934/199842609-80cff204-3062-4358-b5d5-2a831bbfce40.png">

### Debug Message

```plain
"First, install the ESP-IDF Prerequisites for MacOS
restart Visual Studio Code and run this wizard again."
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment] 2022-11-04 08:04
The issue is fixed in master. This is a duplicate of #813

**Closed** 2022-11-07 09:06 UTC
Labels: duplicate, bug-report
