### ISSUE TITLE
[Bug Report]: Build messages in terminal is enabled after compilation errors (VSC-857)

### ISSUE THREAD

**Issue by eos1d3** [espressif/vscode-esp-idf-extension#665] opened 2022-03-10 16:37 UTC
**Describe the bug**

VSCode Version 1.4 disables build message by default. However after a compilation error, the build message will always be enabled after next project buid.

**To Reproduce**
Use any simple example, build it and no build message is shown. Then make a typo error in the example, you will be error message in build message in terminal.

Now, fix the typo, and you will still see the build message in terminal for all next build.

**Expected behavior**
No build message if no compilation error.

**Environment (please complete the following information):**

- OS Name & Version: [e.g. MacOS X 10.14.5]
- VSCode Version: [1.4]
- ESP-IDF Version: [v4.4]
- Python Version: [3.9.10]

PS: A little feature request, it is clean to hide those build messages, but please show the progress in the build status window so that we can what is going on.

**Comment by brianignacio5** [comment] 2022-03-14 14:37
Thanks for reporting this, will take a look !

**Comment by brianignacio5** [comment] 2022-04-02 11:40
I'm unable to reproduce your issue by following your steps. Seems to be more of a vscode issue  itself but can't reproduce it so far.

**Comment by eos1d3** [comment] 2022-04-04 20:51
@brianignacio5 Hi, Just test with two computers. And one of them is just setup with anything new. And the problem is exactly the same as the one having this issue.

To see the issue, please watch:

https://www.youtube.com/watch?v=D3_oO902bns

In the video, I used Blink as example. It complied without error. Then I typed something to create error. And finally undo everything and re-complied again. And you can see build messages in terminal was enabled now.

**Comment by brianignacio5** [comment] 2022-04-06 00:58
The thing is, in your video example, the build task  terminal is already shown and since you didn't close it after the error it will be  reused. Say you fix the issue, close the terminal and then run build again. It will not be shown automatically. I'll see if it is possible to clean the terminal first.

We don't show an status report because we haven't figure out how to get the stdout from the executing task yet, vscode api doesn't expose such task child process feature yet AFAIK.

**Comment by brianignacio5** [comment] 2022-04-07 16:56
Could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/205620688.zip) ?

**Comment by eos1d3** [comment] 2022-04-07 17:45
Installed and tested with the following results:

1. Without setting `idf.notificationSilentMode`, or `idf.notificationSilentMode": true` the build message is always shown.

2. Changing this parameter from `true` o `false`, it still shows the message. To make it works, I need to restart VS Code. Clicking the  `ESP-IDF Monitor Device` icon without restart also works.

3. Changing this parameter from `false` o `true`, no VS Code restart is required and it works immediately.

**Comment by brianignacio5** [comment] 2022-04-08 06:47
I think most users actually want to see the build output normally. For 1and 3 i think that's the expected case.

For 2, when you try to build with an error in the source code, the error notification will appear. After the error is fixed, and the build is run again, the task will clean the previous build output and execute the new one. This is visible because the terminal is already shown to the user. But if the terminal is closed before fixing the issue in source code, fix the issue and then run the build again, the terminal is not shown just the progress notification.

Isn't this the behavior you expected ?

**Comment by eos1d3** [comment] 2022-04-08 08:23
Agree. I do not mind seeing the build output. And this change is more consistent and make sense than current release. 

Thanks for keep the extension better and better!

**Comment by brianignacio5** [comment] 2022-04-09 07:25
Thanks for your feedback, is very important for us to make this better for everyone :)

**Closed** 2022-04-13 16:17 UTC
Labels: vscode related problem, cant reproduce, bug-report
