### ISSUE TITLE
No framework selected to load examples. (VSC-656)

### ISSUE THREAD

**Issue by bhavikbhansali** [espressif/vscode-esp-idf-extension#404] opened 2021-05-10 07:20 UTC
I have installed the ESP-IDF in VS Code and during installation, I didn't get any error. But when I try to use the command ESP-IDF: Show Example Projects it gives "No framework selected to load examples." Can you please help me with this?

**Comment by brianignacio5** [comment] 2021-05-10 08:11
This seems to be a duplicate of #383 

Please comment here if this is different from your issue.

**Closed** 2021-05-13 09:44 UTC
Labels: duplicate
