### ISSUE TITLE
[Feature Request]:  Add ESP32S3 Builtin JTAG to known boards list (VSC-994)

### ISSUE THREAD

**Issue by Panometric** [espressif/vscode-esp-idf-extension#826] opened 2022-10-26 22:03 UTC
**Is your feature request related to a problem? Please describe.**
As a new user of the ESP32-box, I found it very difficult to get the debugger running. 

Note this sounds similar to https://github.com/espressif/vscode-esp-idf-extension/issues/812 but that was closed without an actual solution. 

**Describe the solution you'd like**
When using the extension to configure openocd, the esp32s3 built-in variant should be on the list. 

**Describe alternatives you've considered**
Selected setting for ESP32C3 which is very similar, and then edited the settings manually. 

**Additional context**
Mainstream product should be in this list:
![image](https://user-images.githubusercontent.com/716218/198147077-e54def3d-0de2-4b0e-995e-a4348fe32d34.png)

**Comment by brianignacio5** [comment] 2022-10-27 05:23
The boards listed in the extension are obtained from `esp-config.json` from OpenOCD. The issue is fixed in OpenOCD master as discussed in #812. When you are using the extension you can manually define the values with custom board or use the openOCD version that includes the built-in esp32 S3 config files value.

**Comment by Panometric** [comment] 2022-10-27 20:46
I have the capability to use openocd form the command line using `openocd -f board/esp32s3-builtin.cfg` . The problem is just with that the extension does showing not show it, per the screenshot above from 
extension v1.5.0. 

I understand I can get around it, but it was difficult to figure out.

**Comment by brianignacio5** [comment] 2022-11-01 08:34
The issue should be fixed with the [OpenOCD v0.11.0-esp32-20221026](https://github.com/espressif/openocd-esp32/releases/tag/v0.11.0-esp32-20221026). 

As described in the documentation, you can also manually define the `idf.openOcdConfigs` configuration setting to `board/esp32s3-builtin.cfg`.

I'll make the option for manual input with the `Custom board`

**Closed** 2022-11-07 08:46 UTC
Labels: Feature / Enhancement Request
