### ISSUE TITLE
[Bug Report]:  (VSC-832)

### ISSUE THREAD

**Issue by Enemias-Itzep** [espressif/vscode-esp-idf-extension#630] opened 2022-02-05 05:16 UTC
Everytime I try to configure the extension using the command palatte I get this.
![image](https://user-images.githubusercontent.com/58480376/152629682-53960999-a3ad-4b45-8962-af308691da67.png)

I have tried restarted VS Code, restarting the PC, reinstalling VS Code and none of it worked.

**Comment by sbg97** [comment] 2022-02-06 00:22
Did you look at https://github.com/espressif/vscode-esp-idf-extension/issues/602?

**Comment by brianignacio5** [comment] 2022-02-07 04:00
I'm closing this issue since it is a duplicate of #602

**Closed by brianignacio5** 2022-02-07 04:00 UTC
Labels: duplicate, bug-report
