### ISSUE TITLE
Debugging broke in 0.3.0 (VSC-371)

### ISSUE THREAD

**Issue by meltdown03** [espressif/vscode-esp-idf-extension#132] opened 2020-06-21 00:25 UTC
After upgrading to 0.3.0, debugging doesn't start. I don't get any errors, I just see the debug controls at the top for a fraction of a second and then disappear. OpenOCD and Debug Adapter don't start. Even setting debug type to cppdbg or MI in launch.json don't work unless I revert to the last version of vscode-esp-idf-extension. I re-ran the configuration, still nothing.
Here is log file:
[esp_idf_vsc_ext.log](https://github.com/espressif/vscode-esp-idf-extension/files/4808745/esp_idf_vsc_ext.log)

**Comment by Monkeyinapocket** [comment] 2020-06-22 21:15
I can confirm this issue. It appears on Windows and Linux machines.

**Comment by venon1983** [comment] 2020-06-23 05:24
Yes, I have same trouble. Because this problem, I had to make downgrade.

**Comment by brianignacio5** [comment] 2020-06-23 07:57
On launch.json, can you try changing:

`"PYTHONPATH": "${command:espIdf.getExtensionPath}/esp_debug_adapter/debug_adapter"`

to

`"PYTHONPATH": "**ESP_IDF_EXTENSION_FOLDER**/esp_debug_adapter/debug_adapter"`

Or please try #134 and see if it fixes the issue. For some reason it is not resolving the command.

**Comment by venon1983** [comment] 2020-06-23 08:11
Thaks, it was helpful. Now looks everything correct.

**Closed** 2020-06-23 11:32 UTC
Labels: bug
