### ISSUE TITLE
Com Port Not Changed (VSC-797)

### ISSUE THREAD

**Issue by Xylopyrographer** [espressif/vscode-esp-idf-extension#587] opened 2021-12-06 04:59 UTC
Issue Type: <b>Bug</b>

Visual Code Studio, macOS 11.6, Espressif IDF extension v1.2.0

Selecting the board com port from the tool bar at the bottom brings up a list of connected devices. Selecting the port the board is connected to correctly shows a `Port has been updated to /dev/cu.usbserial-0001` message (in this case this is the port I want), but the toolbar is still showing `/dev/cu.URT1`. Thus when the ESP-IDF, Build, Flash and Monitor icon in the tool bar is selected, it fails to upload as it attempts to connect to the wrong port.

Extension version: 1.2.0
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
vscop804:30404766
vs360cf:30404996
vsrem710:30405998
vscexrecpromp3t3:30407764

```

</details>

**Comment by brianignacio5** [comment] 2021-12-06 06:34
This is a duplicate of #579 and #554 fixed in GitHub master.

There is a setting called `idf.saveScope` that specifies where settings are saved. Change it to workspace folder to save the serial port in your project's settings.json

**Closed by brianignacio5** 2021-12-06 06:34 UTC
Labels: duplicate, Issue Template Ignored
