### ISSUE TITLE
Default baud rate is 460800 in monitor in extension v1.6.2 (VSC-1109)

### ISSUE THREAD

**Issue by rtheil-growlink** [espressif/vscode-esp-idf-extension#970] opened 2023-05-12 21:35 UTC
### OS

Windows

### Operating System version

Windows 10

### Visual Studio Code version

Latest

### ESP-IDF version

4.3.5

### Python version

3.8.7

### Doctor command output

N/A

### Description

Monitor no longer works because baud rate is set as 406800 instead of the necessary 115200

### Debug Message

```plain
See image
```

### Other Steps to Reproduce

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/96268167/4d89a371-c5af-486d-b90d-cf8215502f2c)

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by phfbertoleti** [comment] 2023-05-13 22:45
For reference, I'm experiencing the same error here.

**Comment by dpslwk** [comment] 2023-05-15 02:49
see #963

**Comment by brianignacio5** [comment] 2023-05-15 04:13
Closing this issue since it is a duplicate of #963

**Closed by brianignacio5** 2023-05-15 04:13 UTC
Labels: bug-report
