### ISSUE TITLE
VScode  one-click script to configure esp-idf does not download the tool chain correctly for linux-arm64. (VSC-1024)

### ISSUE THREAD

**Issue by longcat99** [espressif/vscode-esp-idf-extension#861] opened 2022-12-31 23:53 UTC
VScode  one-click script to configure esp-idf does not download the tool chain correctly for linux-arm64.

**Comment by brianignacio5** [comment] 2023-01-03 03:04
This is a duplicate of #840

**Closed by brianignacio5** 2023-01-03 03:04 UTC
Labels: Feature / Enhancement Request

**Comment by brianignacio5** [comment] 2023-01-04 03:40
Could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/runs/3834819964/esp-idf-extension.vsix.zip) ?
